using System;

using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.VisualStudio.Services.Client;
using Microsoft.VisualStudio.Services.DelegatedAuthorization;
using Microsoft.VisualStudio.Services.DelegatedAuthorization.Client;
using Microsoft.VisualStudio.Services.WebApi;

namespace NonInteractivePatGenerationSample
{
    public class Program
    {
        // This is the resource ID for the VSTS application - don't change this.
        private const string VstsResourceId = "499b84ac-1321-427f-aa17-267ca6975798";

        public static void Main(string[] args)
        {
            var username = "[your AAD username]"; // This is your AAD username in the form user@domain.com.
            var password = "[your AAD password]"; // This is your AAD password.
            var aadApplicationID = "[your AAD application ID]"; // Created when you register an AAD application: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications.

            var adalCredential = new UserPasswordCredential(username, password);

            var authenticationContext = new AuthenticationContext("https://login.microsoftonline.com/common");
            var result = authenticationContext.AcquireTokenAsync(VstsResourceId, aadApplicationID, adalCredential).Result;

            var token = new VssAadToken(result);
            var vstsCredential = new VssAadCredential(token);

            var connection = new VssConnection(new Uri("https://[your VSTS account name].visualstudio.com"), vstsCredential);
            var client = connection.GetClient<DelegatedAuthorizationHttpClient>();

            var pat = client.CreateSessionToken(
                displayName: "Generated by sample code",
                tokenType: SessionTokenType.Compact,
                scope: "vso.work"
                ).Result;

            Console.WriteLine(pat.Token);
        }
    }
}
